export enum SORT {
  ADDED = 'ADDED',
  UPDATED = 'UPDATED',
  MOST_VOLUME = 'MOST_VOLUME',
  LEAST_VOLUME = 'LEAST_VOLUME',
  MOST_LIKES = 'MOST_LIKES',
  MOST_COMMENTS = 'MOST_COMMENTS',
  MOST_SHARES = 'MOST_SHARES',
  NEWEST = 'NEWEST',
  OLDEST = 'OLDEST',
}
